In [2]:
import numpy as np
import math

In [23]:
class LinearPolarizer:
    def __init__(self):
        
        self.x = np.array([[1], [0]])
        self.y = np.array([[0], [1]])
    
    def horizontal_vertical(self, bit):
        if bit == 0:
            return self.x
        else:
            return self.y
    
    def diagonal_polarization(self, bit):
        jones = (1/np.sqrt(2))*np.array([[1,1],[1,-1]])
        
        if bit == 0:
            return np.dot(jones, self.x)
        else:
            return np.dot(jones, self.y)
    
    def general_polarization(self, angle, basis):
        """
            angle to be in degrees
        """
        angle = (math.pi/180) * (angle)
        jones = np.array([[np.cos(angle), np.sin(angle)], [np.sin(angle), -np.cos(angle)]])
        
        return np.dot(jones, basis)

class PolarizingBeamSplitter:
    def __init__(self):
        pass
    
    #TODO: add an additional rotation before measurement in case of diagonal basis measurement by Bob
    def measure(self, vector):
        horizontal = np.array([[1, 0], [0, 0]])
        vertical = np.array([[0, 0], [0, 1]])
        
        zero = np.dot(horizontal, vector)
        one = np.dot(vertical, vector)
        
        return {0: zero, 1: one}

In [15]:
lp = LinearPolarizer()

In [5]:
lp.horizontal_vertical(0)

array([[1],
       [0]])

In [6]:
lp.diagonal_polarization(0)

array([[0.70710678],
       [0.70710678]])

In [7]:
lp.diagonal_polarization(1)

array([[ 0.70710678],
       [-0.70710678]])

In [16]:
lp.general_polarization(45, lp.x)

array([[0.70710678],
       [0.70710678]])

In [18]:
pbs = PolarizingBeamSplitter()

In [21]:
pbs.measure(lp.x)

{0: array([[1],
        [0]]), 1: array([[0],
        [0]])}

In [22]:
pbs.measure(lp.diagonal_polarization(0))

{0: array([[0.70710678],
        [0.        ]]), 1: array([[0.        ],
        [0.70710678]])}